"""Orchestration logic for autonomous idea generation."""

import logging
import random
import tempfile
from datetime import UTC, datetime

from project_forge.config import settings
from project_forge.engine.dedup import filter_and_save
from project_forge.engine.generator import IdeaGenerator
from project_forge.engine.quality_review import review_idea
from project_forge.engine.scorer import is_high_value, score_idea
from project_forge.models import GenerationRun, Idea, IdeaCategory
from project_forge.scaffold.builder import build_scaffold_spec, render_scaffold
from project_forge.scaffold.github import create_issue, create_label, create_repo, push_initial_commit
from project_forge.storage.db import Database

logger = logging.getLogger(__name__)

ALL_CATEGORIES = list(IdeaCategory)


async def pick_category(db: Database) -> IdeaCategory:
    """Pick a category, avoiding recent repeats and saturated categories."""
    recent = await db.get_recent_categories(limit=3)
    available = [c for c in ALL_CATEGORIES if c.value not in recent]
    if not available:
        available = ALL_CATEGORIES

    # Check saturation — deprioritize categories with 0 unused tuples
    weighted: list[tuple[IdeaCategory, float]] = []
    for cat in available:
        unused_tuple_count = await db.get_unused_tuple_count(cat)
        weight = max(unused_tuple_count, 1)  # minimum weight of 1
        weighted.append((cat, weight))

    total = sum(w for _, w in weighted)
    choices = [c for c, _ in weighted]
    weights = [w / total for _, w in weighted]
    return random.choices(choices, weights=weights, k=1)[0]


async def generate_and_store(db: Database, generator: IdeaGenerator) -> Idea:
    """Generate one idea, score it, and store it."""
    category = await pick_category(db)
    recent_ideas_objs = await db.list_ideas(limit=5)
    recent_names = [i.name for i in recent_ideas_objs]

    # Alternate between prompt modes for variety
    run_count = await db.count_ideas()
    use_contrarian = run_count % 3 == 1
    use_combinatoric = run_count % 3 == 2

    run = GenerationRun(category=category)

    try:
        idea = await generator.generate(
            category=category,
            recent_ideas=recent_names,
            use_contrarian=use_contrarian,
            use_combinatoric=use_combinatoric,
        )
        result = review_idea(idea)
        if not result.passed:
            logger.warning("Idea '%s' rejected by quality review: %s", idea.name, "; ".join(result.reasons))
            run.error = f"Quality review failed: {'; '.join(result.reasons)}"
            run.completed_at = datetime.now(UTC)
            await db.save_run(run)
            return None
        # Independent scoring
        corpus = await db.list_ideas(limit=50)
        scores = score_idea(idea, corpus=corpus)
        idea.feasibility_score = scores["composite"]

        # Dedup gate
        _, accepted, reason = await filter_and_save(idea, db)
        if not accepted:
            logger.info("Idea '%s' filtered by dedup: %s", idea.name, reason)
            run.error = f"Filtered: {reason}"
            run.completed_at = datetime.now(UTC)
            await db.save_run(run)
            return None
        run.idea_id = idea.id
        run.success = True
        run.completed_at = datetime.now(UTC)
        await db.save_run(run)
        logger.info("Generated and stored idea: %s", idea.name)
        return idea
    except Exception as e:
        run.error = str(e)
        run.completed_at = datetime.now(UTC)
        await db.save_run(run)
        raise


async def create_github_issue_for_idea(idea: Idea) -> str:
    """Create a GitHub issue for the idea and return the URL."""
    repo = f"{settings.github_owner}/{settings.github_repo}"

    # Ensure labels exist
    create_label(repo, "idea", "0e8a16", "Generated project idea")
    create_label(repo, idea.category.value, "1d76db", f"Category: {idea.category.value}")

    body = f"""## {idea.tagline}

**Category:** {idea.category.value}
**Feasibility Score:** {idea.feasibility_score:.2f}

### Description
{idea.description}

### Market Analysis
{idea.market_analysis}

### MVP Scope
{idea.mvp_scope}

### Tech Stack
{", ".join(idea.tech_stack)}

---
*Generated by Project Forge at {idea.generated_at.strftime("%Y-%m-%d %H:%M UTC")}*
"""
    url = create_issue(repo, f"[Idea] {idea.name}", body, labels=["idea", idea.category.value])
    return url


def scaffold_project(idea: Idea) -> str | None:
    """Scaffold a project from an idea. Returns the repo URL or None."""
    spec = build_scaffold_spec(idea)
    with tempfile.TemporaryDirectory() as tmpdir:
        from pathlib import Path

        project_dir = render_scaffold(spec, idea, Path(tmpdir))
        try:
            repo_url = create_repo(spec.repo_name, idea.tagline)
            push_initial_commit(str(project_dir), repo_url)

            # Create initial issues
            full_repo = f"{settings.github_owner}/{spec.repo_name}"
            for issue in spec.initial_issues:
                create_issue(full_repo, issue["title"], issue["body"], labels=["feature"])

            return repo_url
        except RuntimeError as e:
            logger.error("Failed to scaffold %s: %s", spec.repo_name, e)
            return None


async def run_full_cycle(db: Database, generator: IdeaGenerator) -> Idea:
    """Run a complete generation cycle: generate -> issue -> maybe scaffold."""
    idea = await generate_and_store(db, generator)

    # Create GitHub issue
    try:
        issue_url = await create_github_issue_for_idea(idea)
        await db.update_idea_urls(idea.id, github_issue_url=issue_url)
        logger.info("Created GitHub issue: %s", issue_url)
    except Exception as e:
        logger.error("Failed to create GitHub issue: %s", e)

    # Auto-scaffold if high value
    if is_high_value(idea, settings.auto_scaffold_threshold):
        logger.info("Idea %s scored %.2f, auto-scaffolding...", idea.name, idea.feasibility_score)
        repo_url = scaffold_project(idea)
        if repo_url:
            await db.update_idea_urls(idea.id, project_repo_url=repo_url)
            await db.update_idea_status(idea.id, "scaffolded")
            logger.info("Scaffolded project: %s", repo_url)

    return idea
